# Generated by Django 5.1.4 on 2025-01-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_name', models.TextField(max_length=50)),
                ('team_name', models.TextField(max_length=50)),
                ('phone', models.TextField(default='X')),
                ('activity', models.TextField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='attending',
            name='phoneNumber',
            field=models.TextField(default='X'),
        ),
    ]
