# Generated by Django 5.1.4 on 2025-01-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invite', '0002_events_attending_phonenumber'),
    ]

    operations = [
        
    ]
